name: Playwright Tests

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: testuser
          POSTGRES_PASSWORD: testpassword
          POSTGRES_DB: smartscheduler_test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Install Playwright Browsers
      run: npx playwright install --with-deps

    - name: Set up test environment
      run: |
        cp .env.example .env || echo "No .env.example found"
        echo "DATABASE_URL=postgresql://testuser:testpassword@localhost:5432/smartscheduler_test" >> .env
        echo "SESSION_SECRET=test-secret-key-for-ci" >> .env
        echo "NODE_ENV=test" >> .env

    - name: Run database migrations
      run: npm run db:push
      continue-on-error: true

    - name: Run Playwright tests
      run: npm test
      env:
        CI: true

    - name: Upload Playwright Report
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30

    - name: Upload Test Results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-results
        path: test-results/
        retention-days: 30

    - name: Comment PR with test results
      uses: daun/playwright-report-comment@v3
      if: always() && github.event_name == 'pull_request'
      with:
        report-path: playwright-report/index.html
